# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Thu Aug 26 00:00:26 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 302)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spinBoxUsedMemory = QtGui.QSpinBox(self.groupBox_3)
        self.spinBoxUsedMemory.setReadOnly(True)
        self.spinBoxUsedMemory.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxUsedMemory.setPrefix("")
        self.spinBoxUsedMemory.setMaximum(999999999)
        self.spinBoxUsedMemory.setObjectName("spinBoxUsedMemory")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxUsedMemory)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonErase = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonErase.setObjectName("pushButtonErase")
        self.horizontalLayout_2.addWidget(self.pushButtonErase)
        self.pushButtonDownload = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.horizontalLayout_2.addWidget(self.pushButtonDownload)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBoxMode = QtGui.QComboBox(self.groupBox_4)
        self.comboBoxMode.setObjectName("comboBoxMode")
        self.comboBoxMode.addItem("")
        self.comboBoxMode.addItem("")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxMode)
        self.labelSize = QtGui.QLabel(self.groupBox_4)
        self.labelSize.setObjectName("labelSize")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelSize)
        self.spinBoxSize = QtGui.QSpinBox(self.groupBox_4)
        self.spinBoxSize.setMaximum(9)
        self.spinBoxSize.setObjectName("spinBoxSize")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxSize)
        self.labelOrientation = QtGui.QLabel(self.groupBox_4)
        self.labelOrientation.setObjectName("labelOrientation")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelOrientation)
        self.comboBoxOrientation = QtGui.QComboBox(self.groupBox_4)
        self.comboBoxOrientation.setObjectName("comboBoxOrientation")
        self.comboBoxOrientation.addItem("")
        self.comboBoxOrientation.addItem("")
        self.comboBoxOrientation.addItem("")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxOrientation)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.pushButtonSetMode = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonSetMode.setObjectName("pushButtonSetMode")
        self.verticalLayout_2.addWidget(self.pushButtonSetMode)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.spinBoxFirmwareVersion = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxFirmwareVersion.setReadOnly(True)
        self.spinBoxFirmwareVersion.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxFirmwareVersion.setMaximum(65535)
        self.spinBoxFirmwareVersion.setObjectName("spinBoxFirmwareVersion")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxFirmwareVersion)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBoxAnalogVersion = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxAnalogVersion.setReadOnly(True)
        self.spinBoxAnalogVersion.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxAnalogVersion.setMaximum(65535)
        self.spinBoxAnalogVersion.setObjectName("spinBoxAnalogVersion")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxAnalogVersion)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spinBoxPadVersion = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxPadVersion.setReadOnly(True)
        self.spinBoxPadVersion.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxPadVersion.setMaximum(65535)
        self.spinBoxPadVersion.setObjectName("spinBoxPadVersion")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxPadVersion)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_5.setBuddy(self.spinBoxUsedMemory)
        self.label_4.setBuddy(self.comboBoxMode)
        self.labelSize.setBuddy(self.spinBoxSize)
        self.labelOrientation.setBuddy(self.comboBoxOrientation)
        self.label.setBuddy(self.spinBoxFirmwareVersion)
        self.label_2.setBuddy(self.spinBoxAnalogVersion)
        self.label_3.setBuddy(self.spinBoxPadVersion)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listWidget, self.groupBox)
        MainWindow.setTabOrder(self.groupBox, self.spinBoxUsedMemory)
        MainWindow.setTabOrder(self.spinBoxUsedMemory, self.pushButtonErase)
        MainWindow.setTabOrder(self.pushButtonErase, self.pushButtonDownload)
        MainWindow.setTabOrder(self.pushButtonDownload, self.comboBoxMode)
        MainWindow.setTabOrder(self.comboBoxMode, self.spinBoxSize)
        MainWindow.setTabOrder(self.spinBoxSize, self.comboBoxOrientation)
        MainWindow.setTabOrder(self.comboBoxOrientation, self.pushButtonSetMode)
        MainWindow.setTabOrder(self.pushButtonSetMode, self.spinBoxFirmwareVersion)
        MainWindow.setTabOrder(self.spinBoxFirmwareVersion, self.spinBoxAnalogVersion)
        MainWindow.setTabOrder(self.spinBoxAnalogVersion, self.spinBoxPadVersion)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "M210", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Used memory:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxUsedMemory.setSuffix(QtGui.QApplication.translate("MainWindow", " B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonErase.setText(QtGui.QApplication.translate("MainWindow", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDownload.setText(QtGui.QApplication.translate("MainWindow", "Save...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "TABLET", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "MOUSE", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSize.setText(QtGui.QApplication.translate("MainWindow", "Tablet size:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOrientation.setText(QtGui.QApplication.translate("MainWindow", "Tablet orientation:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOrientation.setItemText(0, QtGui.QApplication.translate("MainWindow", "NW", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOrientation.setItemText(1, QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOrientation.setItemText(2, QtGui.QApplication.translate("MainWindow", "NE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetMode.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Version information", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Firmware version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Analog version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Pad version:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

