#!/usr/bin/python
# -*- coding: utf-8 -*-

# m210
# Copyright © 2010 Tuomas Räsänen (tuos) <tuos@codegrove.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

# Standard modules.
import os.path
import sys

# Third-party modules
import dbus.exceptions

# Project modules.
import m210.optparse
import m210.pegatech

USAGE = '%prog [OPTION]... [DIRECTORY]'
DESCRIPTION = 'Export notes as SVG files.'

if __name__ == "__main__":
    parser = m210.optparse.OptionParser(usage=USAGE, description=DESCRIPTION)

    parser.add_option("--verbose", "", action="store_true", default=False,
                      help="print processing messages")
    parser.add_option("--input", "", dest="file",
                      help="read notes from FILE instead of stdin")

    options, args = parser.parse_args(sys.argv)

    try:
        output_dirpath = os.path.abspath(args[1])
    except IndexError:
        output_dirpath = os.path.abspath(".")

    if options.file:
        input_file = open(options.file, "rb")
    else:
        input_file = sys.stdin

    m210.pegatech.export_notes_as_svgs(input_file, output_dirpath)
